wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/quick.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/quiet.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rabbit.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rabies.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/raccoon.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/radio.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/radish.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rain-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rain.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/raincoat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rainy.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/raisins.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rape.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/raspberry.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/read-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ready.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/real.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/receive-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/recent.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/recipe.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/record-player.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/record.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/red.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/refrigerator.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/regret-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/regulation.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/reindeer.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rel-greater-than.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rel-smaller-than.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/relative.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/religion.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/religious.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/remember-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/remember.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/remembrance-day.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/repair-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/reproduction.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/request-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/resent-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/resident.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/residentialinstitution.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/resourcecenter.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/respect.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rest-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rest.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/restaurant.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/return-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/return.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rhinoceros.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rhyme.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rhythm-method.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ribbon.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rice.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rich.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ride-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rifle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/right.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rightmorally.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rim-wheel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ring.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rise-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/river.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/road-runner.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rocket.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rocking-horse.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/roll.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/roof.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/room.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/roots.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rosh-hashana.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/roti.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rouge.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/rub-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ruler.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/run-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/s.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/s2.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/s2not.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sabbath.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sad.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sadness.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/safe.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/safety.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sail.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sailboat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sailor.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/salad.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/saliva.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/salt.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sand.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sandals.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sandwich.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sanitary-napkin.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sari.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/satisfaction.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/saturday.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sauce.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sauerkraut.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sauna.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sausage.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/saw.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/say-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/scales.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/scarf.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/scenery.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/schach.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/schedule.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/school.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/science.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/scissors.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/scorpion.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/screw.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/screwdriver.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/scrotum.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/search-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/second-time.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/second.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/secret.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/secretary.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/see-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/see-you-again.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/seed.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/seem-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/self-abuse.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/self-control.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/self.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/selfish.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sell-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/semen.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/seminal-vesicle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/send-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sentence.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/several.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sew-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sewing-machine.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sewing-needle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sex-drive.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sex.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sexual-abuse.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sexual-arousal.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sexual-harassment.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sexual-intercourse.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sexual-pleasure.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sexuality.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shake-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shallow.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shame.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shampoo.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shamrock.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/share-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shark.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sharp.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shave-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shaver.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shaving-soap.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shavuot.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/she.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sheep.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shekel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shelter.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shirt.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shiva.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shoes.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shofar.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shopping-center.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/short.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shorts.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/should-mind-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/should-mind.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/should-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/should.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shoulder.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shouldnot-mind-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shouldnot-mind.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shouldnot-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shouldnot.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shout-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shovel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/show-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shower-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shower.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/shvat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sibling.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sick.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/side.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sieve.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sign.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/silence.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/silent.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/simchat-torah.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/similar-sound.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/simmer-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sin.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sing-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/singer.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sinner.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sister.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sit-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/skeleton.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ski-boots.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/skin.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/skirt.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/skull-cap.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/skunk.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sky.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sleep-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sleep.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sleeping-bag.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/slide.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/slip.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/slippers.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/slow.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/small.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/smart.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/smash-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/smile-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/smoke-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/smoke.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snake.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sneeze-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snow-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snow.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snowball.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snowflake.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snowman.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snowstorm.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/snowsuit.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/soap.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/social-worker.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/socks.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/soldier.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/solve-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/some.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sometimes.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/son.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/song.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/songbird.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/soon.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sore.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sorry.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/soufganiya.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/soul.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sound-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sound.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/soup.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/south.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/southern.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spaghetti.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/special.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/specific.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/speech-impaired.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sperm.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spice-box.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spider.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spit-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/splash-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spoon.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sport.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spot.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spread-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spread.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/spring.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/squash.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/squirrel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/staff.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stairs.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stand-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stander.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/standing-person.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/star.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/starfish.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/start-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stay-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/steam-bath.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/steam-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/steam.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/steel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stepfather.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stepmother.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sterilization.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stick.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stomach.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stone.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/store.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/storeroom.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/storm.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/story.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/strange.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stranger.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/strap.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/strawberry.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/street.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/string-bean.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/strong.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/student.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/stupid.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/subtract-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/success.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/suddenly.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sugar.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/suggest-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/suggestion.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/suit.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sukkah.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sukkot.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/summer-day-camp.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/summer.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sun-screen.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sun.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sunday.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sunny.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sunrise.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sunset.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/support.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/surprise-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swallow-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swamp.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swan.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sweat-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sweat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sweden.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sweet-potato.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sweet.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sweetheart.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swim-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swimsuit.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swing-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/swing.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/switch-on-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/sword.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/symbol-display.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/synagogue.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/table-game.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/table.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tablecloth.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tahini.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/take-away-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/take-off.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/take-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/talcum-powder.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tallit.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tamuz.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tangerine.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tape-recorder.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/taxi-driver.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/teach-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/teach.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/teacher.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/team.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tease-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/teenager.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/teeth.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/telephone.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/television.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/temperature.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tent.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/terrified-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/terrorist.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/terrorize-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/test.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/testicle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tevet.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tfillim.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thank-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thanks.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thanksgiving.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/that.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thats-too-bad.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thatstoobad.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thaw-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/the-netherlands.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/the-public.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/the.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/theater.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/their-female.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/their-human.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/their-male.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/their.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/then.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/therapist.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/there.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/therefore.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thermometer.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thermos.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/these.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/they-female.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/they-human.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/they-male.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/they.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thick.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thin.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thing.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/think-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/this-week.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/this.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/those.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thoughtless.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/through.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/throw-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thumb.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thunder.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/thursday.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ticket.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tie.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tiger.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/time.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tiptoe-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tire.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tired.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tisha-bav.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tissue.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/to-and-fro.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toast-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toast.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toaster.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tobacco.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/today.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toe.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/together.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toilet-paper.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toilet.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tomato.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tomorrow-night.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tomorrow.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tongue.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tonight.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/too-much.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tool.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toothbrush.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toothpaste.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/top.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/torah.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/touch-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/towards.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/towel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toy-animal.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/toy.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tractor.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/traffic.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/train.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/translate-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/transport-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/travel-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/treat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tree.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tricycle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/trip.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/trouble.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/truck.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/true.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/trunk.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/trust-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/trust.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/truth.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/try-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tu-bshvat.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tuesday.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/tune.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/turkey.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/turkey2.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/turn-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/turn.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/turnip.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/turtle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/twinkle-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/typewriter.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/ugly.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/umbrella.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/uncle-aunt.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/uncle.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/uncomfortable.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/under.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/underground-shelter.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/underpants.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/undershirt.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/understand.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/underwear.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/unemployment.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/unidentified-object.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/united-kingdom.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/university.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/unless.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/until.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/up-and-down.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/up-right.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/up.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/upset.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/urethra.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/urinate-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/urine.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/use-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/usually.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/utensil.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vacation.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vagina.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/valentine.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/valentines-day.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/valley.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/value.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/veal.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/veg-above-ground.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/veg-below-ground.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vegetable-above-ground.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vegetable-below-gr.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vegetable-below-ground.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/video-recorder.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/village.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vinegar.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/virginity.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vishnu.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/visit-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/visitor.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/visually-impaired.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/visuallyimpaired.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/volcano.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/volunteer.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vomit-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/voyeurism.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/vulture.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wages.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wagon.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/waist.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wait-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/walk-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/walker.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wall.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/want-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/war.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/warm.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wash-cloth.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wash-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/washable.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/washing-machine.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/waste.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/watch-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/watch.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/watchful.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/water-snake.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/water.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/we.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/weak.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/weather.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/weave-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wednesday.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/week.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/weigh-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/weight.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/welcome.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/west.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/western.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wet.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/whale.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/what-kind-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/what-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/what-thing-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/what.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wheel.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wheelchair.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/when-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/when.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/where-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/where.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/which-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/which.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/whisper-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/whistle-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/white.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/who-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/who.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/whose-person.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/whose-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/whose.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/why-q.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wife.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wiggly.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wild-animal.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wild-bird.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wild-flower.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wind.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/window.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wings.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/winter-rainy.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/winter.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wipe-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wire.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wish-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wolf.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/woman.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wood.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wool.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/word.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/work-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/work.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/workbook.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/worker.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/world.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/worm.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/worry-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/worry.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/would.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wrestling.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wrist.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wristwatch.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/write-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/wrongmorally.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yahrzeit.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yard.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yawn-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yell-v.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yellow.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yen.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yes.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yesterday.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yogurt.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/yom-kippur.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/you-female.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/you-male-plural.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/you-male.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/you-plural.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/you.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/young.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/your-female-plural.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/your-female.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/your-male-plural.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/your-male.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/your-plural.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/your.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/youre-welcome.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/zebra.jpg
wget http://www.symbols.net/blissymbolics/dictionary/dictionary_images/zoo.jpg
